#!/bin/bash
file_count=&(ls -l | wc -l)

train_part = file_count / 10 * 6
valid_part = file_count / 10 * 2
test_part = file_count / 10 * 2

mkdir train;
mkdir validation;
mkdir test;

num=1
for i in *.png; do
	new=$(printf "%d.png" "$num")
	mv "$i" "$new"
	let num=num+1
done

# number all the files

for ((i = 0; i < train_part; i++); do
	mv i ./train
done

for ((i = $train_part; i < train_part + valid_part; i++); do
	mv i ./validation
done

for ((i = $train_part + valid_part; i < file_count; i++); do
	if [[ -e i ]]; then
		mv i ./test
	fi
done

# 60/20/20 ratio.
